"""create users

Revision ID: 927fd34de516
Revises:
Create Date: 2025-12-16 09:52:56.206229

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "927fd34de516"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
