"""add lists table

Revision ID: c4d55122373b
Revises: ca9ff53f0032
Create Date: 2026-01-15 11:01:04.122240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4d55122373b"
down_revision: str | Sequence[str] | None = "ca9ff53f0032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["boards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        op.f("board_members_board_id_fkey"), "board_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "board_members", "boards", ["board_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "board_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("board_members_board_id_fkey"),
        "board_members",
        "boards",
        ["board_id"],
        ["id"],
    )
    op.drop_table("lists")
    # ### end Alembic commands ###
