"""create boards and board_members

Revision ID: ca9ff53f0032
Revises: d7ba0a18e933
Create Date: 2025-12-17 12:30:31.503545

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca9ff53f0032"
down_revision: str | Sequence[str] | None = "d7ba0a18e933"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "boards",
        sa.Column(
            "background_kind", sa.String(), nullable=False, server_default="gradient"
        ),
    )
    op.add_column("boards", sa.Column("background_value", sa.String(), nullable=True))
    op.add_column(
        "boards", sa.Column("background_thumb_url", sa.String(), nullable=True)
    )

    op.create_table(
        "board_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["boards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("board_members")
    op.drop_table("boards")
    op.drop_column("boards", "background_thumb_url")
    op.drop_column("boards", "background_value")
    op.drop_column("boards", "background_kind")

    # ### end Alembic commands ###
